language: python
sudo: required
dist: trusty
before_install:
  - openssl aes-256-cbc -K $encrypted_a0717c12b42e_key -iv $encrypted_a0717c12b42e_iv -in gcp-travisci.json.enc -out gcp-travisci.json -d
  - echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551
  - sudo apt-get update -qq && sudo apt-get install google-cloud-sdk
  - gcloud auth activate-service-account --key-file gcp-travisci.json
install:
  - gcloud config set project project-kel
  - ./scripts/ci/deps.sh
script:
  - ./scripts/ci/build.sh
after_success:
  - ./scripts/ci/deploy.sh
