apiVersion: v1
kind: Service
metadata:
  name: api-cache
  namespace: kel-system
  labels:
    kelproject.com/name: api-cache
    kelproject.com/cluster-service: "true"
spec:
  selector:
    kelproject.com/name: api-cache
  ports:
    - port: 6379
      protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-cache-{{ version }}
  namespace: kel-system
  labels:
    kelproject.com/name: api-cache
    version: {{ version }}
spec:
  replicas: {{ replicas }}
  selector:
    kelproject.com/name: api-cache
    version: {{ version }}
  template:
    metadata:
      labels:
        kelproject.com/name: api-cache
        version: {{ version }}
    spec:
      containers:
        - name: redis
          image: {{ image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/redis
              name: api-cache-persistent-storage
      nodeSelector:
        kelproject.com/node-kind: node-1x
      volumes:
        - name: api-cache-persistent-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: {{ cluster.config["name"] }}-api-cache
