apiVersion: v1
kind: Service
metadata:
  name: api-cache
  namespace: kel-system
  labels:
    {{ cluster.config["managed-by"] }}/name: api-cache
    {{ cluster.config["managed-by"] }}/cluster-service: "true"
spec:
  selector:
    {{ cluster.config["managed-by"] }}/name: api-cache
  ports:
    - port: 6379
      protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-cache
  namespace: kel-system
  labels:
    {{ cluster.config["managed-by"] }}/name: api-cache
    version: {{ version }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      {{ cluster.config["managed-by"] }}/name: api-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ cluster.config["managed-by"] }}/name: api-cache
        version: {{ version }}
    spec:
      containers:
        - name: redis
          image: {{ image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: api-cache-persistent-storage
      nodeSelector:
        {{ cluster.config["managed-by"] }}/node-kind: node-1x
      volumes:
        - name: api-cache-persistent-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: {{ cluster.config["name"] }}-api-cache
